#!/bin/sh
if [ "$1" = "up" ]; then nmap -sP 10.0.0.1-255 > shell.output
elif [ "$1" = "ip" ]; then ssh 10.0.0.2 ifconfig tun0 > shell.output
elif [ "$1" = "uname" ]; then uname -ar > shell.output
elif [ "$1" = "vnc" ]; then 
	ssh 10.0.0.2 vncserver 
	echo VNC server started > shell.output
else echo Unknown command > shell.output
fi
